
schemaName: sharding_db

dataSourceCommon:
 username: root
 password: 123456
 connectionTimeoutMilliseconds: 30000
 idleTimeoutMilliseconds: 60000
 maxLifetimeMilliseconds: 1800000
 maxPoolSize: 5
 minPoolSize: 1
 maintenanceIntervalMilliseconds: 30000

dataSources:
 ds_0:
   url: jdbc:mysql://127.0.0.1:3306/mall_0?serverTimezone=UTC&useSSL=false
 ds_1:
   url: jdbc:mysql://127.0.0.1:3306/mall_1?serverTimezone=UTC&useSSL=false

rules:
- !SHARDING
 tables:
   s_order:
     actualDataNodes: ds_${0..1}.s_order_${0..15}
     tableStrategy:
       standard:
         shardingColumn: id
         shardingAlgorithmName: s_order_inline
     keyGenerateStrategy:
       column: id
       keyGeneratorName: snowflake
 bindingTables:
   - s_order
 defaultDatabaseStrategy:
   standard:
     shardingColumn: order_id
     shardingAlgorithmName: database_inline
 defaultTableStrategy:
   none:
 
 shardingAlgorithms:
   database_inline:
     type: INLINE
     props:
       algorithm-expression: ds_${order_id % 2}
   s_order_inline:
     type: INLINE
     props:
       algorithm-expression: s_order_${id % 16}
   
 
 keyGenerators:
   snowflake:
     type: SNOWFLAKE
     props:
       worker-id: 123
